### ISSUE TITLE
Mechanization is errored on server startup

### ISSUE THREAD

**Issue by MrBot45** [ImCoolYeah105/Mechanization#105]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
The one specified in the installation section. Mechanization_v2.3.0a.zip MechConfig_v2.3.0.zip DatapackUtilities_v2.2.0b.zip

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
It's says Loaded Datapack Utils v2.2.0b, Loaded Datapack Mechanization v2.3.0a

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
On a normal minecraft world that got freshly generated on vanilla multiplayer.

4. What if happening vs. what you expect to happen?
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_3
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandExecute.b(SourceFile:123) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_2
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandSummon.a(SourceFile:38) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_7
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandLoot.a(SourceFile:73) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_8
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandExecute.b(SourceFile:123) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:52] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[17:23:52] [main/WARN]: Missing data pack file/ICY105_CombinedPack_r6.zip
[17:23:53] [main/INFO]: Reloading ResourceManager: Default, bukkit, MechConfig_v2.3.0.zip, Mechanization_v2.3.0a.zip, DatapackUtilities_v2.2.1.zip
[17:23:53] [Worker-Main-14/INFO]: Loaded 7 recipes
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_3
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandExecute.b(SourceFile:123) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_2
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandSummon.a(SourceFile:38) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_7
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandLoot.a(SourceFile:73) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:387) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:391) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more
[17:23:54] [Worker-Main-14/ERROR]: Failed to load function mechanization:assembly/machines/compressor/recipes_8
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_16_R2.command.VanillaCommandWrapper.getPermission(VanillaCommandWrapper.java:90) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:135) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CommandExecute.b(SourceFile:123) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:357) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:347) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunction.a(SourceFile:55) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.CustomFunctionManager.a(SourceFile:86) ~[spigot.jar:git-Spigot-379750e-43c7ff9]
        ... 6 more

Im using spigot 1.16.1, i tried spigot 1.16.2 and both get errored.

**Comment by ImCoolYeah105** [comment]
My best guess is spigot is throwing a fit about some new 1.16 feature that isn't stable yet. The good news is if appears the errors only affect the Compressor machine, so you should be able to safely ignore the errors and use the datapack until spigots fixes itself.

The bad news is I can't fix spigot bugs, sorry.

**Comment by MrBot45** [comment]
A friend is running the datapack on his server and we cant make any guns, sometime when we try to make one, we get kicked for minecraft:speed character error. We cant make Reinforced Structural Ingot tho.

Also, would it be possible for you to update the thinker table documentation on how to use it with the new version. We can't figure out how it works.

**Comment by ImCoolYeah105** [comment]
1. The speed issue is likely another spigot bug, as I've never seen it happen before
2. Tier 3 alloys, including Reinforced Structural Ingot, require the Alloy Furnace to have a Machine Upgrade.
3. I just released an update to the Tinker Table UI which makes it much less confusing.

**Comment by MrBot45** [comment]
Ok thanks, I will test it out!

**Comment by MrBot45** [comment]
New issue, the Control Rod doesnt work with a redstone signal anymore. I can only activate it with a lever placed on it. I can't use it with a redstone signal...

**Comment by MrBot45** [comment]
Also give instruction for the quarry, It's telling me "Incomplete boundary" everytime. I cant get it to work
